# Generated by Django 5.2.17 on 2026-09-25 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCentre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(db_index=True, help_text='City or primary location area', max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diagnostic Centre',
                'verbose_name_plural': 'Diagnostic Centres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category', models.CharField(db_index=True, default='General', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('preparation_instructions', models.TextField(blank=True, help_text='e.g., 10-hour fasting required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diagnostic Test',
                'verbose_name_plural': 'Diagnostic Tests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CentreTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='Test price at this specific centre', max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('estimated_hours', models.PositiveIntegerField(default=24, help_text='Report turnaround time in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_tests', to='centres.diagnosticcentre')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_centres', to='centres.diagnostictest')),
            ],
            options={
                'verbose_name': 'Centre Test Pricing',
                'verbose_name_plural': 'Centre Test Pricings',
                'ordering': ['centre', 'test'],
                'unique_together': {('centre', 'test')},
            },
        ),
    ]
