# Generated by Django 5.2.17 on 2026-09-25 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('booking_reference', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('DUPLICATE', 'Duplicate Ignored'), ('FAILED', 'Failed')], default='PROCESSED', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], db_index=True, default='PENDING', max_length=20)),
                ('payment_method', models.CharField(default='SIMULATED_CARD', max_length=50)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
